# Omit irrelavent processes to speed up the simulation
/rat/physics_list/OmitMuonicProcesses true
/rat/physics_list/OmitHadronicProcesses true

#Set the detector geometry and noise rate database entries used in the simulation
/rat/db/set DETECTOR geo_file "geo/snoplusnative.geo"
#/rat/db/load OPTICS_labppo.ratdb
#/rat/db/load MATERIALS_labppo.ratdb
# Chose average PMT noise rate to be 450.Hz
/rat/db/set NOISE_RUN_LEVEL average_noiserate 450.0d

# #Begin Event loop and the processors to be run on each event
/run/initialize
# /rat/proc outroot
# /rat/procset file "snoplus_electrons_1MeV_p2.root"


# #Now specify the events to generate and pass to the event loop
# /generator/add combo gun:fill:poisson
# /generator/vtx/set e- 0 0 0 1.0
# /generator/pos/set 0.0 0.0 0.0
# /generator/rate/set 1

#start the simulation with 100 events
/rat/run/start 4



exit