/rat/physics_list/OmitMuonicProcesses true
/rat/physics_list/OmitHadronicProcesses true

# Use the simple geo for speed up viewing
/rat/db/set DETECTOR geo_file "local_geometries/lsnoplusnative_addbox.geo"

/run/initialize




# BEGIN EVENT LOOP
/rat/proc simpledaq
/rat/proc count
/rat/procset update 10
/rat/proc calibratePMT
/rat/proclast outroot
# END EVENT LOOP.

/generator/add combo pbomb:point:uniform

/generator/vtx/set 5000 500 0 # Already ran
/rat/procset file "pbomb500.root"

/generator/pos/set 34 -21 19 mm
/generator/rate/set 1

# /run/verbose 2
# /event/verbose 2
# /tracking/verbose 2

/rat/run/start 2 #Using 10000 for other geos
exit
